window.dbMoves =
{
  "フレイムバースト": { "type": "fire", "power": 110, "priority": 0, "target": "single", "category": "physical", "desc": "単体攻撃" },
  "ヒートウェーブ": { "type": "fire", "power": 65, "priority": 0, "target": "all_enemies", "category": "physical", "desc": "敵全体攻撃" },
  "アクアストリーム": { "type": "water", "power": 110, "priority": 0, "target": "single", "category": "physical", "desc": "単体攻撃" },
  "マッドウェーブ": { "type": "water", "power": 65, "priority": 0, "target": "all_enemies", "category": "physical", "desc": "敵全体攻撃" },
  "ソーンウィップ": { "type": "grass", "power": 110, "priority": 0, "target": "single", "category": "physical", "desc": "単体攻撃" },
  "カッターウィンド": { "type": "grass", "power": 65, "priority": 0, "target": "all_enemies", "category": "physical", "desc": "敵全体攻撃" },
  "ホーリーレイ": { "type": "light", "power": 100, "priority": 0, "target": "single", "category": "physical", "desc": "単体攻撃" },
  "フラッシュバン": { "type": "light", "power": 65, "priority": 0, "target": "all_enemies", "category": "physical", "desc": "敵全体攻撃" },
  "ダークインパクト": { "type": "dark", "power": 100, "priority": 0, "target": "single", "category": "physical", "desc": "単体攻撃" },
  "ダークミスト": { "type": "dark", "power": 65, "priority": 0, "target": "all_enemies", "category": "physical", "desc": "敵全体攻撃" },
  "ラッシュ": { "type": "normal", "power": 90, "priority": 0, "target": "single", "category": "physical", "desc": "無属性の単体攻撃" },
  "ドレインバイト": { "type": "water", "power": 70, "priority": 0, "target": "single", "category": "physical", "effect": "drain", "desc": "与えたダメージの50％を回復" },
  "光速の爪": { "type": "light", "power": 60, "priority": 1, "target": "single", "category": "physical", "desc": "先制攻撃(優先度+1)" },
  "カウンター": { "type": "normal", "power": 0, "priority": -3, "target": "self", "category": "status", "effect": "counter", "desc": "最後に受けたダメージを1.5倍で返す(優先度-3)" },
  "プロテクション": { "type": "normal", "power": 0, "priority": 4, "target": "self", "category": "status", "effect": "protect", "desc": "先制ですべての技を完全に防ぐが連発すると成功率30%に" },
  "パワーチャージ": { "type": "normal", "power": 0, "priority": 0, "target": "ally", "category": "status", "effect": "buff_atk", "desc": "味方単体のATK上昇" },
  "アイアンシェル": { "type": "normal", "power": 0, "priority": 0, "target": "ally", "category": "status", "effect": "buff_def", "desc": "味方単体のDEF上昇" },
  "アクセルステップ": { "type": "normal", "power": 0, "priority": 0, "target": "ally", "category": "status", "effect": "buff_spd", "desc": "味方単体のSPD上昇" },
  "インティミデイト": { "type": "normal", "power": 0, "priority": 0, "target": "all_enemies", "category": "status", "effect": "debuff_atk", "desc": "敵全体のATK下降" },
  "アシッドボム": { "type": "normal", "power": 0, "priority": 0, "target": "all_enemies", "category": "status", "effect": "debuff_def", "desc": "敵全体のDEF下降" },
  "スパイダーネット": { "type": "normal", "power": 0, "priority": 0, "target": "all_enemies", "category": "status", "effect": "debuff_spd", "desc": "敵全体のSPD下降" },
  "ヒールライト": { "type": "light", "power": 0, "priority": 0, "target": "ally", "category": "status", "effect": "heal", "desc": "味方単体のHPを30％回復" },
  "グラスヒール": { "type": "grass", "power": 0, "priority": 0, "target": "all_allies", "category": "status", "effect": "heal", "heal_percent": 0.2, "desc": "味方全体のHPを20％回復" },
  "ディストーション": { "type": "dark", "power": 0, "priority": -5, "target": "field", "category": "status", "effect": "trick_room", "desc": "5ターン素早さ順序逆転(優先度-5)" },
  "アクアダッシュ": { "type": "water", "power": 70, "priority": 0, "target": "single", "category": "physical", "side_effect": "buff_spd_self", "desc": "攻撃後、自分のSPD上昇" },
  "アイスホーン": { "type": "water", "power": 100, "priority": 0, "target": "single", "category": "physical", "special_type": "ice", "desc": "水技だが草に弱点、炎に半減" },
  "猛吹雪": { "type": "water", "power": 65, "priority": 0, "target": "all_enemies", "category": "physical", "special_type": "ice", "desc": "敵全体攻撃。水技だが草に弱点、炎に半減" },
  "グラスファング": { "type": "grass", "power": 140, "priority": 0, "target": "single", "category": "physical", "side_effect": "debuff_def_self", "desc": "高威力だが攻撃後に自分のDEF下降" },
  "ドレインホーン": { "type": "dark", "power": 70, "priority": 0, "target": "single", "category": "physical", "effect": "drain", "desc": "与えたダメージの50％を回復" },
  "ハーフカット": { "type": "normal", "power": 0, "priority": 0, "target": "single", "category": "special_damage", "effect": "half_hp", "desc": "敵の現在HPを半分にする" },
  "ボルトクロー": { "type": "light", "power": 140, "priority": 0, "target": "single", "category": "physical", "side_effect": "debuff_def_self", "desc": "高威力だが攻撃後に自分のDEF下降" },
  "マグマブロック": { "type": "fire", "power": 80, "priority": 0, "target": "single", "category": "physical", "side_effect": "buff_def_self", "desc": "攻撃後、自分のDEF上昇" },
  "アルティメットレイ": { "type": "light", "power": 110, "priority": 0, "target": "all", "category": "physical", "desc": "敵味方全員を攻撃する強い光" },
  "キラーダイブ": { "type": "dark", "power": 70, "priority": 0, "target": "single", "category": "physical", "effect": "full_hp_double", "desc": "相手のHPがMAXなら威力2倍" },
  "カースドノヴァ": { "type": "dark", "power": 130, "priority": 0, "target": "single", "category": "physical", "side_effect": "debuff_spd_self", "desc": "高威力だが攻撃後に自分のSPD下降" },
  "クイックファイア": { "type": "fire", "power": 60, "priority": 1, "target": "single", "category": "physical", "desc": "先制攻撃(優先度+1)" },
  "ヘルブレード": { "type": "fire", "power": 140, "priority": 0, "target": "single", "category": "physical", "side_effect": "debuff_def_self", "desc": "高威力だが攻撃後に自分のDEF下降" },
  "ライトブレード": { "type": "light", "power": 130, "priority": -1, "target": "single", "category": "physical", "desc": "高威力だが後攻になる" },
  "アクアブロック": { "type": "water", "power": 80, "priority": 0, "target": "single", "category": "physical", "side_effect": "buff_def_self", "desc": "攻撃後、自分のDEF上昇" },
  "ロックパンチ": { "type": "fire", "power": 60, "priority": 0, "target": "single", "category": "physical", "side_effect": "buff_atk_self", "desc": "攻撃後、自分のATK上昇" },
  "グラスダッシュ": { "type": "grass", "power": 100, "priority": 0, "target": "single", "category": "physical", "side_effect": "buff_spd_self", "desc": "攻撃後、自分のSPD上昇" },
  "ダークファング": { "type": "dark", "power": 140, "priority": 0, "target": "single", "category": "physical", "side_effect": "debuff_def_self", "desc": "高威力だが攻撃後に自分のDEF下降" },
  "スパイラルブロウ": { "type": "water", "power": 70, "priority": 0, "target": "single", "category": "physical", "effect": "full_hp_double", "desc": "相手のHPがMAXなら威力2倍" },
  "花粉爆発": { "type": "grass", "power": 110, "priority": 0, "target": "all", "category": "physical", "desc": "敵味方全員を攻撃する花粉攻撃" },
  "ぱちぱちパーティ": { "type": "fire", "power": 110, "priority": 0, "target": "all", "category": "physical", "desc": "敵味方全員を攻撃する火花攻撃" },
  "ポイズンアロー": { "type": "grass", "power": 30, "priority": 0, "target": "single", "category": "physical", "side_effect": "poison_target", "desc": "攻撃後、相手を毒状態にする" },
  "ポイズンスプレー": { "type": "fire", "power": 30, "priority": 0, "target": "single", "category": "physical", "side_effect": "poison_target", "desc": "攻撃後、相手を毒状態にする" },
  "ひっくりダイス": { "type": "dark", "power": 0, "priority": 0, "target": "any_single", "category": "status", "effect": "reverse_stats", "desc": "選択した1体のステータス変化を逆転" },
  "ダウンダイス": { "type": "dark", "power": 60, "priority": 0, "target": "single", "category": "physical", "side_effect_target": "debuff_def_target", "desc": "攻撃後、相手のDEF下降" },
  "ドレインローズ": { "type": "fire", "power": 70, "priority": 0, "target": "single", "category": "physical", "effect": "drain", "desc": "与えたダメージの50％を回復" },
  "セイントスタンプ": { "type": "light", "power": 60, "priority": 0, "target": "single", "category": "physical", "side_effect": "buff_atk_self", "desc": "攻撃後、自分のATK上昇" },
  "もふガード": { "type": "grass", "power": 0, "priority": 0, "target": "ally", "category": "status", "effect": "buff_def", "desc": "味方単体のDEF上昇" },
  "弱点解析": { "type": "dark", "power": 60, "priority": 0, "target": "single", "category": "physical", "side_effect": "buff_atk_self", "desc": "攻撃後、自分のATK上昇" },
  "クイックシャドウ": { "type": "dark", "power": 60, "priority": 1, "target": "single", "category": "physical", "desc": "先制攻撃(優先度+1)" },
  "足払い": { "type": "normal", "power": 60, "priority": 0, "target": "single", "category": "physical", "side_effect_target": "debuff_spd_target", "desc": "攻撃後、相手のSPD下降" },
  "疾風の棘": { "type": "grass", "power": 60, "priority": 1, "target": "single", "category": "physical", "desc": "先制攻撃(優先度+1)" },

  "プチファイア": { "type": "fire", "power": 40, "priority": 0, "target": "single", "category": "physical", "adventure_only": true, "desc": "弱い炎の単体攻撃" },
  "アクアショット": { "type": "water", "power": 40, "priority": 0, "target": "single", "category": "physical", "adventure_only": true, "desc": "弱い水の単体攻撃" },
  "リーフショット": { "type": "grass", "power": 40, "priority": 0, "target": "single", "category": "physical", "adventure_only": true, "desc": "弱い草の単体攻撃" },
  "ミニレイ": { "type": "light", "power": 35, "priority": 0, "target": "single", "category": "physical", "adventure_only": true, "desc": "弱い光の単体攻撃" },
  "シャドウタッチ": { "type": "dark", "power": 35, "priority": 0, "target": "single", "category": "physical", "adventure_only": true, "desc": "弱い闇の単体攻撃" },
  "タックル": { "type": "normal", "power": 30, "priority": 0, "target": "single", "category": "physical", "adventure_only": true, "desc": "弱い無属性の単体攻撃" }
}